In [ ]:
# lst=[5,10,15,20]
[x*x for x in lst]

In [5]:
list(map(lambda x: x*x,lst))

[25, 100, 225, 400]

In [7]:
import pandas as pd
s=pd.Series(lst)
def func(x):
    return x*x
s.apply(func)

0     25
1    100
2    225
3    400
dtype: int64

In [8]:
for i in lst:
    print(i*i)

25
100
225
400


In [9]:
import numpy as np
a=np.array(lst)

In [10]:
a*a

array([ 25, 100, 225, 400])

#### numpy allows us to create vectorised operations
- applying the operation on all the elements.
- conditionally filtering the elements.

### numpy stands for numerical python
- allows us to create arrays and perform vectorisation.
- vectorisation means applying and filtering operations to all the elements of a collection without an explicit loop

In [11]:
type(a)

numpy.ndarray

In [12]:
ls=[50,20,25,30,35,40,90,100]
[x>50 for x in ls]

[False, False, False, False, False, False, True, True]

In [14]:
arr=np.array(ls)
arr[arr>50]

array([ 90, 100])

In [15]:
arr[arr>np.mean(arr)]

array([ 50,  90, 100])

In [17]:
arr.shape

(8,)

In [18]:
arr.ndim

1

In [19]:
#the length of every element in a 1 d array is same and equal to 1


In [20]:
#numpy auto coerces the elements into a simple type
b=np.array(["hi",10,"20",True,4.5])
b

array(['hi', '10', '20', 'True', '4.5'], dtype='<U4')

In [21]:
#there fore all the elements are converted to string

In [22]:
c=np.array([10,20,True, False])
c

array([10, 20,  1,  0])

In [23]:
len(b[0])

2

In [24]:
len(b[1])

2

In [25]:
len(b[3])

4

In [27]:
#in a.shape we dont use paranthesis , because shape is the property of the array and not method.

In [28]:
#no of dimensions =no of brackets or the last value of shape

In [7]:
import numpy as np
a3d=np.array([[[1,2,3],[4,5,6]] , [[7,8,9],[10,11,12]]])
print(a3d.shape)
print(a3d.ndim)
a3d

(2, 2, 3)
3


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [8]:
a3d=np.array([[[1,2,3],[4,5,6],[13,14,15]] , [[7,8,9],[10,11,12]]])
print(a3d.shape)
print(a3d.ndim)
print(a3d)
type(a3d)

(2,)
1
[list([[1, 2, 3], [4, 5, 6], [13, 14, 15]])
 list([[7, 8, 9], [10, 11, 12]])]


numpy.ndarray

In [35]:
a3d=np.array([[[1,2,3],[4,5]] , [[7,8,9],[10,11,12]]])
print(a3d.shape)
print(a3d.ndim)
print(a3d)

(2, 2)
2
[[list([1, 2, 3]) list([4, 5])]
 [list([7, 8, 9]) list([10, 11, 12])]]


In [38]:

a=np.array([[1,2,3,4],[5,6,7,8]])
a-np.mean(a)

array([[-3.5, -2.5, -1.5, -0.5],
       [ 0.5,  1.5,  2.5,  3.5]])

In [39]:
a[a<np.mean(a)]

array([1, 2, 3, 4])

In [40]:
a1d=np.array([10,20,30,40,50,60,70,90,100])
print(a1d[0:3])
print(a1d[-1])
print(a1d[0:6:2])
print(a1d[::-1])

[10 20 30]
100
[10 30 50]
[100  90  70  60  50  40  30  20  10]


In [45]:
a2d=np.array([[10,10,1],[7,8,75]])
print(a2d[0,1])
print(a2d[:,2])
print(a2d[1,:])

10
[ 1 75]
[ 7  8 75]


In [47]:
a3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3d[0])
print(a3d[0,1])
print(a3d[1,1,1])

[[1 2 3]
 [4 5 6]]
[4 5 6]
11


In [51]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a>b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[False False False False]


In [52]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[11,12,13],[14,15,16],[17,18,19]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a>b)

[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]
[[False False False]
 [False False False]
 [False False False]]


In [53]:
#matrix multiplication
#number of columns of first matrix should be equal to number of columns of the second.
#np.dot(mat1,mat2)
#mat1@mat2 --> both the matrices should be two dimensional

In [58]:
mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.dot(mat1,mat1))
print(mat1@mat1)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [63]:
mat1=np.array([[[1,2,3],[4,5,6],[1,2,3]],[[7,8,9],[10,11,12],[1,2,3]]])
print(np.dot(mat1,mat1))
print("______")
print(mat1@mat1)

[[[[ 12  18  24]
   [ 30  36  42]]

  [[ 30  45  60]
   [ 84  99 114]]

  [[ 12  18  24]
   [ 30  36  42]]]


 [[[ 48  72  96]
   [138 162 186]]

  [[ 66  99 132]
   [192 225 258]]

  [[ 12  18  24]
   [ 30  36  42]]]]
______
[[[ 12  18  24]
  [ 30  45  60]
  [ 12  18  24]]

 [[138 162 186]
  [192 225 258]
  [ 30  36  42]]]


In [65]:
mat1=np.array([[1]])
mat2=np.array([[1],[2],[3]])
print(mat1.ndim,mat2.ndim)
print(mat2@mat1)

2 2
[[1]
 [2]
 [3]]


In [67]:
mat1=np.array([1])
mat2=np.array([1,2,3])
print(mat1.ndim,mat2.ndim)
#print(mat2@mat1)
#it throws an error because mat1 is not of 1 X 1 and mat2 is not of 1 X 3

1 1


In [72]:
#CREATE A 4 X 3 matrix and find the transpose
mat=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(mat)
print(mat.shape)
tr=np.transpose(mat)
print(tr.shape)
print(tr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
(3, 4)
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [75]:
#flatten : it converts an higher dimensional array to a one dimensional array.
print(mat)
print(mat.flatten())

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
x=np.array([1,2,3,4,5,6,7,8])
print(x.reshape(2,4))
print(x.reshape(2,2,2))

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
mat1=np.array([[[1,2,3],[4,5,6],[1,2,3]],[[7,8,9],[10,11,12],[1,2,3]]])
print(mat1.ndim)
mat1.reshape(9,2).ndim

3


2

In [84]:
a=np.array([10,20,30,40])
print(a.reshape(1,-1)) #is similar to a.reshape(1,4)
print(a.reshape(-1,1)) #is similar to a.reshape(4,1)

[[10 20 30 40]]
[[10]
 [20]
 [30]
 [40]]


#### assume you are given a very big array which is one dimensional , you have to convert it to a two dimensional one , with one column and rows.To do this we have to compute the total number of elements and then reshape it , instead we can use a.reshape(1,-1)

In [90]:
#what are the different ways to cut this array into n equal parts.
a2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.split(a2d,3,axis=0))
#print(np.split(a2d,4,axis=0)) will give an error
#when we specify axis=0 , it splits row -wise

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [95]:
a=np.split(a2d[0:2,],2,axis=0)
print(a)
print(a2d)

[array([[1, 2, 3]]), array([[4, 5, 6]])]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [100]:
a2d=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,2],[1,4,5,6]])
split1=np.array(np.split(a2d,2,axis=0))

mat1=np.split(split1[0],2,axis=1)[0]
mat2=np.split(split1[0],2,axis=1)[1]
print(mat1)
print(mat2)

[[1 2]
 [4 5]]
[[3 4]
 [6 7]]


### concatenation of arrays

In [104]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[3,4,5],[6,7,8],[11,23,34]])
print(np.concatenate((arr1,arr2),axis=0)) #concatenates row-wise
print(np.concatenate((arr1,arr2),axis=1)) #concatenates column-wise

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 3  4  5]
 [ 6  7  8]
 [11 23 34]]
[[ 1  2  3  3  4  5]
 [ 4  5  6  6  7  8]
 [ 7  8  9 11 23 34]]


In [105]:
#to concatenates two arrays with axis=0, the number of columns in both the arrays should be same.
##to concatenates two arrays with axis=1, the number of rows in both the arrays should be same.


In [106]:
#vstack is concatenation on axis=0
#hstack is concatenation on axis=1

In [108]:
a1d=np.array([[1,2,3],[4,5,6]])
a2d=np.array([[11,12,13],[14,15,16]])
np.vstack((a1d,a2d))
#np.concatenates((a1d,a2d),axis=0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [109]:
a1d=np.array([[1,2,3],[4,5,6]])
a2d=np.array([[11,12,13],[14,15,16]])
np.hstack((a1d,a2d))
#np.concatenates((a1d,a2d),axis=1)


array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])